# Generated by Django 3.1.7 on 2021-03-17 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('username', models.CharField(max_length=200)),
                ('userid', models.IntegerField()),
                ('advisorname', models.CharField(max_length=200)),
                ('advisorid', models.IntegerField()),
            ],
        ),
    ]
