# Generated by Django 3.1.7 on 2021-03-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor_name', models.TextField(max_length=200)),
                ('advisor_url', models.URLField()),
            ],
        ),
    ]
